include:
  - template: Jobs/Secret-Detection.gitlab-ci.yml
  - project: 'infrastructure/renovate-bot'
    file: 'renovate-config-validator.gitlab-ci.yml'
  # General Kaniko items at the moment
  - /.gitlab-ci/kaniko.yml

stages:
 - build
 - test

build_container_image:
  extends: .kaniko_build

build_latest_image:
  extends: .kaniko_build
  variables:
    CONTAINER_BUILD_DESTINATIONS: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE:latest
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
