include:
  # This should enable pipelines to run on default branches and MRs only
  - template: Workflows/MergeRequest-Pipelines.gitlab-ci.yml
  - template: Jobs/Secret-Detection.gitlab-ci.yml
  - project: 'infrastructure/renovate-bot'
    file: 'renovate-config-validator.gitlab-ci.yml'
    rules:
      - changes:
        - renovate.json
        - .gitlab/renovate.json

  # Container Specific pipelines are below
  # - project: 'infrastructure/ci'
  #   file: 'templates/trivy.gitlab-ci.yml'
  - component: $CI_SERVER_HOST/ci/components/kaniko/kaniko@1.2.2
  - component: $CI_SERVER_HOST/ci/components/trivy/container@1.0.4

variables:
  SLSA_PROVENANCE_SCHEMA_VERSION: v1

stages:
 - build
 - test

# scan_container_image:
#   extends: .trivy_scan
#   # This should run all the time and should always use the $CI_COMMIT_SHORT_SHA variable since `latest` is
#   # just another tag of the same image
#   # rules:
#   #   - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
