.kaniko_build:
  stage: build
  variables:
    CONTAINER_BUILD_CONTEXT: $CI_PROJECT_DIR
    CONTAINER_BUILD_DOCKERFILE: $CONTAINER_BUILD_CONTEXT/Dockerfile
    CONTAINER_BUILD_DESTINATIONS: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    KANIKO_CACHE_ARGS: --cache=true --cache-copy-layers=true --cache-ttl=24h
    KANIKO_BUILD_ARGS: ""
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  # before_script:
  #   - mkdir -p /kaniko/.docker
  script:
    - /kaniko/executor
      --context "${CONTAINER_BUILD_CONTEXT}"
      --dockerfile "${CONTAINER_BUILD_DOCKERFILE}"
      ${KANIKO_CACHE_ARGS} ${KANIKO_BUILD_ARGS}
      $(for DEST in $CONTAINER_BUILD_DESTINATIONS; do echo "--destination $DEST"; done)

# .kaniko_build_tag:
#   extends: .kaniko_build
#   variables:
#     CONTAINER_BUILD_DESTINATIONS: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
#   rules:
#     - if: $CI_COMMIT_TAG

